other: true
server:
  port: 8081
application:
  title: boot项目
spring:
    profiles:
        active: redis,other
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/bootDemo
        username: root
        password: root
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath*:mapping/*Mapper.xml


db:
  ds:
    main:
      name: test2
      jdbc-url: jdbc:mysql://127.0.0.1:3306/bootDemo
      url: jdbc:mysql://127.0.0.1:3306/bootDemo
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    db1:
      name: test
      url: jdbc:mysql://127.0.0.1:3306/zlb_test1
      jdbc-url: jdbc:mysql://127.0.0.1:3306/zlb_test1
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
    db2:
      name: test2
      jdbc-url: jdbc:mysql://127.0.0.1:3306/zlb_test2
      url: jdbc:mysql://127.0.0.1:3306/zlb_test2
      username: root
      password: root
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
my:
  myserver:
    server:
     - server1
     - server2
