server:
  port: 8761

eureka:
  instance:
    hostname: @eureka.instance.hostname@
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: @defaultZone@
  server:
      ##自我保护模式
      enable-self-preservation: false

spring:
  application:
    name: eureka-server
